# Site settings
title:       Blog
email:       joshherkness@gmail.com
author:      Josh Herkness
description: "Just a students blog"
baseurl:     "/blog"
url:         "http://joshherkness.github.io"

# Google analytics
google_analytics:

# Optional features
animated:           false
show_related_posts: false
show_post_footers:  false

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname:

# Social icons
show_social_icons: false
github_username: joshherkness
stackoverflow_id:
twitter_username:
google_plus_id:
linkedin_username:
bitcoin_url:
paypal_url:
flattr_button:

# Build settings
markdown:     redcarpet
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
highlighter: pygments
permalink:    pretty
paginate:     10
sass:
  compressed: true
  
# Default Post
defaults:
  -
    scope:
      path: "/_posts" # an empty string here means all files in the project
    values:
      layout: "post"
