# Site settings
title:       Blog
email:       joshherkness@gmail.com
author:      Josh Herkness
description: "Just a students blog"
baseurl:     "/journal"
url:         "http://joshherkness.github.io"

# Google analytics
google_analytics:

# Optional features
animated:           false
show_related_posts: true
show_post_footers:  false
show_social_icons:  true
show_rss:						false

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname:

# Social icons
github_username:		joshherkness
stackoverflow_id:
twitter_username:
google_plus_id:
linkedin_username:
bitcoin_url:
paypal_url:
flattr_button:

# Build settings
markdown:     redcarpet
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
highlighter: 	pygments
permalink:    pretty
paginate:     10
sass:
  compressed: true
